name: human_file_size
version: 0.7.0

description: >-
  A robust, customisable package to get a human representation of the size of
  your files.

homepage: https://github.com/vxern/human_file_size
repository: https://github.com/vxern/human_file_size
issue_tracker: https://github.com/vxern/human_file_size/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  decimal: ^3.2.4
  intl: ^0.20.2

dev_dependencies:
  collection: ^1.19.1
  test: ^1.29.0
  words: ^0.5.0
